### PR TITLE
Adding LilygoTWatch2020

### PR DESCRIPTION
**Pull request by Ellerbach**
## Description

Adding LilygoTWatch2020

## Targets affected

- [ ] MBN_QUAIL
- [ ] GHI_FEZ_CERB40_NF
- [ ] I2M_ELECTRON_NF
- [ ] I2M_OXYGEN_NF
- [ ] WEACT_F411CE
- [ ] ST_NUCLEO64_F401RE_NF
- [ ] ST_NUCLEO64_F411RE_NF
- [ ] ST_STM32F411_DISCOVERY
- [ ] ST_NUCLEO144_F412ZG_NF
- [ ] ST_NUCLEO144_F746ZG
- [ ] ST_STM32F4_DISCOVERY
- [ ] ST_NUCLEO144_F439ZI
- [ ] TI_CC1352P1_LAUNCHXL_868
- [ ] TI_CC1352P1_LAUNCHXL_915
- [ ] ESP32_OLIMEX
- [ ] M5Stack
- [ ] M5StickC
- [ ] M5StickCPlus
- [x] LilygoTWatch2020
- [ ] PybStick2x
- [ ] BUILD ALL

## Motivation and Context

- Community request: https://discordapp.com/channels/478725473862549535/481782754674212867/902821923468222464
- We do have the ESP32 build system
- We do have the driver

## How Has This Been Tested?

Needs to be tested by the community memeber

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Ellerbach** [comment]
I will. This is a draft and waiting for one of out contributor to give me a feedback on the image.

**Comment by josesimoes** [comment]
@Ellerbach when you have the opportunity can you please look at this PR? 😝

**Comment by Ellerbach** [comment]
> when you have the opportunity can you please look at this PR?

As there has not been any feedback, is it possible to close the PR and leave the branch? If not possible, then changing this PR to draft? I would prefer to get a feedback that this works before merging. 
Now we can merge as well as it's a community target and then expecting that it works fine :-)

**Comment by Ellerbach** [comment]
> I would vote for the latter. Having it public increases the chances of someone actually using it and provide feedback if anything is broken.

ok, will look at this and adjust accordingly in next few days

**Comment by Ellerbach** [comment]
As this one is an ESP32 based, it should move to the nf-interpreter nightly build as the rest of the ESP32 targets. So I'll close this PR

**Comment by josesimoes** [comment]
> As this one is an ESP32 based, it should move to the nf-interpreter nightly build as the rest of the ESP32 targets. So I'll close this PR

It's OK to have it here! Please don't add another ESP32 on nf-interpreter!! 😱

**Pull request closed without merging**
