### PR TITLE
Updated BrainPad2 and ST_NUCLEO64_F411RE_NF to meet latest changes

### PR DESCRIPTION
**Pull request by valoni**
## Description
Updated nanobooter files
Updated nanoClr files
Updated target_common.h.in files
Updated JSON file

***BrainPad2***
***ST_NUCLEO64_F411RE_NF***

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by networkfusion** [comment]
@valoni The Build_ST_NUCLEO64_F411RE_NF seems to be failing... can you check as to why?

**Comment by valoni** [comment]
updated files but those created 6 single patches for each file

**Review by valoni — COMMENTED** [review]
updated file with new line

**Comment by valoni** [comment]
close it because no need more those to be used.

**Pull request closed without merging**
