### PR TITLE
Add WeAct F411CE board

### PR DESCRIPTION
**Pull request by kyoushuu**
This is to add support for the WeAct F411CE board by WeAct Studio, also known as Black Pill or MiniF4.

Note that this is still a work in progress. I'm also planning to add support for the F401CU and F401CE versions in the future.

## Description
This is based on I2M_OXYGEN_NF. I modified the clock and the pins for the user LED and button.

GitHub repository of WeAct Studio for the board is [here](https://github.com/WeActTC/MiniSTM32F4x1). I used the schematic there to check the details about the pins, comparing it to Oxygen's schematic in the IngenuityMicro's website.

More info about the board available at [STM32-base](https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0.html) (which I used to check details about the clocks) and [Zephyr Project docs](https://docs.zephyrproject.org/latest/boards/arm/blackpill_f411ce/doc/index.html).

I still have to update the README files, the build files and other stuff, but I would like to create the PR now so other people could take a look at it and give me guidance on how to properly port this board. Also note that my experience with embedded programming is mostly with Arduino platform.

## Targets affected

- [ ] MBN_QUAIL
- [ ] GHI_FEZ_CERB40_NF
- [ ] I2M_ELECTRON_NF
- [ ] I2M_OXYGEN_NF
- [x] WEACT_F411CE
- [ ] ST_NUCLEO64_F401RE_NF
- [ ] ST_NUCLEO64_F411RE_NF
- [ ] ST_STM32F411_DISCOVERY
- [ ] ST_NUCLEO144_F412ZG_NF
- [ ] ST_NUCLEO144_F746ZG
- [ ] ST_STM32F4_DISCOVERY
- [ ] ST_NUCLEO144_F439ZI
- [ ] TI_CC1352P1_LAUNCHXL_868
- [ ] TI_CC1352P1_LAUNCHXL_915
- [ ] ALL

(I'm adding a new target, so it is not yet in the list)

## Motivation and Context

The Black Pill board is a well known and low cost board, just like the ESP32 boards. Many users of Blue Pill are now moving to it since there is no chance of getting fake STM32 chips right now, it has better features and costs only a bit more. I believe that it will be a good addition to the supported boards of nanoFramework.

It will be a good alternative to ESP32 when internet connectivity is not needed, or when a good ADC is needed, since the Blue Pill board is not supported by nanoFramework due to its low specs.

## How Has This Been Tested?
I can't build the Oxygen target with the scripts in `install-scripts`, so I used Dev Containers in VS Code.

I built it by follow the instructions [here](https://docs.nanoframework.net/content/building/using-dev-container.html). After step 6, I have to add the following to `linkage.choices` in `.vscode\cmake-variants.json`:

```
      "WEACT_F411CE": {
        "short" : "WEACT_F411CE",
        "settings": {
          "BUILD_VERSION" : "1.2.63.1705",
          "CMAKE_TOOLCHAIN_FILE": "CMake/toolchain.arm-none-eabi.cmake",
          "TOOLCHAIN_PREFIX": "/usr/local/bin/gcc",
          "TOOL_HEX2DFU_PREFIX": "/usr/local/bin/hex2dfu",
          "RTOS": "CHIBIOS",
          "TARGET_SERIES": "STM32F4xx",
          "USE_RNG" : "OFF",
          "RTOS_SOURCE_FOLDER": "/sources/ChibiOs",
          "TARGET_BOARD": "WEACT_F411CE",
          "CHIBIOS_CONTRIB_REQUIRED": "OFF",
          "CHIBIOS_CONTRIB_SOURCE": "/sources/ChibiOs-Contrib",
          "STM32_CUBE_PACKAGE_REQUIRED": "OFF",
          "STM32_CUBE_PACKAGE_SOURCE": "/sources/STM32CubeL4",
          "SUPPORT_ANY_BASE_CONVERSION" : "OFF",
          "SWO_OUTPUT" : "OFF",
          "NF_BUILD_RTM" : "OFF",
          "NF_WP_TRACE_ERRORS" : "OFF",
          "NF_WP_TRACE_HEADERS" : "OFF",
          "NF_WP_TRACE_STATE" : "OFF",
          "NF_WP_TRACE_NODATA" : "OFF",
          "NF_WP_TRACE_ALL" : "OFF",
          "NF_WP_IMPLEMENTS_CRC32" : "OFF",
          "NF_FEATURE_DEBUGGER" : "ON",
          "NF_FEATURE_RTC" : "ON",
          "NF_FEATURE_USE_APPDOMAINS" : "OFF",
          "NF_FEATURE_WATCHDOG" : "ON",
          "NF_FEATURE_HAS_CONFIG_BLOCK" : "OFF",
          "NF_FEATURE_HAS_SDCARD" : "OFF",
          "NF_FEATURE_HAS_USB_MSD" : "OFF",
          "NF_PLATFORM_NO_CLR_TRACE" : "OFF",
          "NF_CLR_NO_IL_INLINE" : "OFF",
          "NF_INTEROP_ASSEMBLIES" : [ ],
          "NF_NETWORKING_SNTP" :  "OFF",
          "NF_SECURITY_OPENSSL" : "OFF",
          "NF_SECURITY_MBEDTLS" : "OFF",
          "MBEDTLS_SOURCE" :  "",
          "API_Hardware.Stm32": "ON",
          "API_Windows.Devices.Gpio": "ON",
          "API_System.Device.Gpio": "ON",
          "API_Windows.Devices.Spi": "ON",
          "API_Windows.Devices.I2c": "ON",
          "API_System.Device.I2c": "ON",
          "API_Windows.Devices.Pwm": "ON",
          "API_Windows.Devices.SerialCommunication": "ON",
          "API_nanoFramework.Devices.OneWire": "OFF",
          "API_nanoFramework.Devices.Can": "OFF",
          "API_nanoFramework.ResourceManager": "ON",
          "API_nanoFramework.System.Collections": "ON",
          "API_nanoFramework.System.Text": "ON"
        }
      }
```

Select `WEACT_F411CE` as target in step 13.

To flash the board, follow the instructions [here](https://docs.nanoframework.net/content/stm32/flash-stlink.html), but you have to use an ST-LINK V2 dongle, and you have to switch to programming mode before doing step 5 and 7. To switch to programming mode, press the `BOOT0` button, press the `NRST` button, release the `NRST` button then release the `BOOT0` button.

Afterwards, disconnect your ST-LINK V2 dongle from the board then connect to it using a USB Type C cable.

I only tested `Blinky` and `Hardware.Stm32\Stm32.ReadDeviceIDs` from the Samples repository for now, both works.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nf-Community-Targets?pullRequest=159) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nf-Community-Targets?pullRequest=159) before we can accept your contribution.<br/><br/>:x: kyoushuu [sign now](https://cla.dotnetfoundation.org/nanoframework/nf-Community-Targets?pullRequest=159)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nf-Community-Targets?pullRequest=159) it.</sub>

**Comment by josesimoes** [comment]
@kyoushuu to have this added to the build please follow this:
1) Edit the azure-pipelines.yml, copy the I2M_OXYGEN_NF section to the bottom and make the necessary changes as you have above for cmake-variants.json (name and other configs). Just don't chage the toolchain ones as the build here runs on Windows.
2) Edit the main readme by copy/paste/edit so that the new target gets listed.
3) Edit the PR template inside .github  folder to add this targets to the check list of targets to build.

Thanks!

**Comment by josesimoes** [comment]
@kyoushuu could you please address the requested above so this can be merged? Thanks!

**Comment by networkfusion** [comment]
@kyoushuu any advance on this?

**Pull request merged**
